#!/usr/bin/python3

import argparse
import logging

import dbus.mainloop.glib
import dbus.service
from gi.repository import GObject

from openfprintd.manager import Manager

dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

if __name__ == '__main__':
    parser = argparse.ArgumentParser('Open fprintd DBus service')
    parser.add_argument('--debug', help='Enable tracing', action='store_true')
    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(level=logging.DEBUG)

    bus_name = dbus.service.BusName('net.reactivated.Fprint', dbus.SystemBus())
    server = Manager(bus_name)

    GObject.MainLoop().run()
