#!/usr/bin/python3

import dbus
import dbus.mainloop.glib
import dbus.service
dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
from gi.repository import GObject
import logging
import argparse

from openfprintd.manager import Manager
from openfprintd.device import Device


if __name__ == '__main__':
    parser = argparse.ArgumentParser('Open fprintd DBus service')
    parser.add_argument('--debug', help='Enable tracing', action='store_true')
    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(level=logging.DEBUG)

    bus_name = dbus.service.BusName('net.reactivated.Fprint', dbus.SystemBus())
    device = Device(bus_name, 'io.github.uunicorn.Fprint', '/io/github/uunicorn/Fprint/Device')
    server = Manager(bus_name, device)

    GObject.MainLoop().run()

